# Generated by Django 4.0.3 on 2022-04-11 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goddamit', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcategories',
            name='name',
            field=models.CharField(max_length=64),
        ),
    ]
